# Generated by Django 4.0.4 on 2022-05-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_question_status_alter_question_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('n', 'Named'), ('a', 'Anonymous')], default='n', max_length=1),
        ),
    ]
